### PR TITLE
Create redshift__create_constraints.sql

### PR DESCRIPTION
**Pull request by ataft**
Create redshift adapter.

Note: Redshift does not allow ALTER COLUMN, so NOT NULL will not work. This means that PRIMARY KEY will also not work, so it is suggested to use UNIQUE KEY.

### CODE REVIEW

**Comment by sfc-gh-dflippo** [comment]
I believe that Redshift allows for [longer identifiers than PostgreSQL?
](https://docs.aws.amazon.com/redshift/latest/dg/r_names.html)

If so, I think we can replace "63" with "127" in the code so that we use meaningful constraint names in most cases. PostgreSQL and Oracle are much more limited by default so their constraints usually end up with a 'UK_' + MD5 string.

**Comment by ataft** [comment]
Yes, confirmed that is the case. Code updated.

**Comment by sfc-gh-dflippo** [comment]
Want to test with the new order in create_constraints or should I merge the PR now?

**Comment by ataft** [comment]
All good, I tested the new order already

**Pull request merged**
